### ISSUE TITLE
Accept chains without placing all of its nodes

### ISSUE THREAD

**Issue by 1995parham** [roadtomsc/simulation#15]
There is a case in which a chain is accepted but one of its nodes is not placed.

Topology:

```yaml
nodes:
- id: core-switch-0
  cores: 0
  ram: 0
  vnfSupport: false
  notManagerNodes: []
  egress: true
  ingress: true
- id: aggr-switch-0-0
  cores: 0
  ram: 0
  vnfSupport: false
  notManagerNodes: []
  egress: false
  ingress: false
- id: edge-switch-0-0
  cores: 0
  ram: 0
  vnfSupport: false
  notManagerNodes: []
  egress: false
  ingress: false
- id: server-0-0
  cores: 20
  ram: 100
  vnfSupport: true
  notManagerNodes:
  - server-1-0
  egress: false
  ingress: false
- id: aggr-switch-1-0
  cores: 0
  ram: 0
  vnfSupport: false
  notManagerNodes: []
  egress: false
  ingress: false
- id: edge-switch-1-0
  cores: 0
  ram: 0
  vnfSupport: false
  notManagerNodes: []
  egress: false
  ingress: false
- id: server-1-0
  cores: 20
  ram: 100
  vnfSupport: true
  notManagerNodes:
  - server-0-0
  egress: false
  ingress: false
links:
- source: core-switch-0
  destination: aggr-switch-0-0
  bandwidth: 40000
- source: core-switch-0
  destination: aggr-switch-1-0
  bandwidth: 40000
- source: aggr-switch-0-0
  destination: edge-switch-0-0
  bandwidth: 40000
- source: edge-switch-0-0
  destination: server-0-0
  bandwidth: 40000
- source: aggr-switch-1-0
  destination: edge-switch-1-0
  bandwidth: 40000
- source: edge-switch-1-0
  destination: server-1-0
  bandwidth: 40000
```

Chains:

```yaml
chains:
  - cost: 10
    nodes:
      - type: vFW
        id: 1
      - type: vNAT
        id: 2
      - type: egress
        id: 3
    links:
      - source: 1
        destination: 2
        bandwidth: 250
```
